### PR TITLE
Two new toaster positions: top middle and bottom middle

### PR DESCRIPTION
**Pull request by danielalexiuc**
Added two new position directions. Useful if you want your toaster to appear in the middle of the page.

### CODE REVIEW

**Comment by kitsonk** [comment]
This is a read only repo and we cannot accept pull requests here.  Please see contribution guidelines at http://dojotoolkit.org/get-involved and utilitse http://bugs.dojotoolkit.org/ for submitting patches.

**Comment by danielalexiuc** [comment]
That's too hard.

Daniel

**Comment by dylans** [comment]
At a minimum, we'll need to verify that you have a CLA on file (you can read and fill out a form online at http://dojofoundation.org/about/claForm  ).

The patch should also make sure it updates the inline documentation (see the inline comment a few lines before your change).

Normally I would ask that you provide a test case to support your proposed enhancement, but the existing test for Toaster is a bit lacking and isn't even updated for AMD, so while I'd like to see that updated, I don't think it should block this enhancement.

Finally, when your patch is accepted into Dojo, I would ask that you also provide an update to the docs at https://github.com/dojo/docs/blob/master/dojox/widget/Toaster.rst

We're trying very hard to not allow our tests and documentation to get out of sync with our code base, so we would appreciate all new patches help with this effort so that we don't get constant complaints about our docs being inaccurate.

Finally, we're still primarily working in svn until Dojo 2.0, so Kitson's comment about submitting bug patches and fixes to http://bugs.dojotoolkit.org/ is the preferred workflow until then, but I'm happy to do that work for you since you feel it's too hard.

-Dylan

**Comment by danielalexiuc** [comment]
Dylan, 
That was a very informative, helpful and measured response to a very trollish kind of comment. You've turned me into a Dojo contributor.

**Comment by dylans** [comment]
Daniel, thanks, we appreciate your help, and I appreciate the kind words! -Dylan

**Comment by ghenry** [comment]
Did this have get merged?

**Comment by dylans** [comment]
I don't think so.

That said, we have fully moved to GitHub now, so this should be done instead inside of https://github.com/dojo/dojox/ , but with a ticket inside of http://bugs.dojotoolkit.org/  . If someone wants to update the patch, based on my feedback above, I will review it.

**Pull request closed without merging**
